// Mocks generated by Mockito 5.4.6 from annotations
// in clean_boilerplate/test/features/settings/domain/usecases/get_locale_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:clean_boilerplate/config/util/result.dart' as _i4;
import 'package:clean_boilerplate/features/settings/domain/entities/theme_mode.dart'
    as _i5;
import 'package:clean_boilerplate/features/settings/domain/repositories/settings_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.AppThemeMode>> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i3.Future<_i4.Result<_i5.AppThemeMode>>.value(
              _i6.dummyValue<_i4.Result<_i5.AppThemeMode>>(
                this,
                Invocation.method(#getThemeMode, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AppThemeMode>>);

  @override
  _i3.Future<_i4.Result<void>> setThemeMode(_i5.AppThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#setThemeMode, [mode]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<String>> getLocale() =>
      (super.noSuchMethod(
            Invocation.method(#getLocale, []),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i6.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#getLocale, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<void>> setLocale(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [localeCode]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#setLocale, [localeCode]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateApiLocale(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#updateApiLocale, [localeCode]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateApiLocale, [localeCode]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
