// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwQobVcGy2xn6dBOKEnQM_Z8Tv07T52I',
    appId: '1:139665999955:web:f48f5a3d02ea8e9b705ea6',
    messagingSenderId: '139665999955',
    projectId: 'mess-management-2600a',
    authDomain: 'mess-management-2600a.firebaseapp.com',
    storageBucket: 'mess-management-2600a.firebasestorage.app',
    measurementId: 'G-RFY9LCW3YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmoS0QeU3YHwHfAZc0lePlgomBeXDIZnU',
    appId: '1:139665999955:android:f82aa29627a8f249705ea6',
    messagingSenderId: '139665999955',
    projectId: 'mess-management-2600a',
    storageBucket: 'mess-management-2600a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eolSVS5fVZEIx27yXXlks-yZQU2Bskk',
    appId: '1:139665999955:ios:37d1a5496abdcb0d705ea6',
    messagingSenderId: '139665999955',
    projectId: 'mess-management-2600a',
    storageBucket: 'mess-management-2600a.firebasestorage.app',
    iosBundleId: 'com.example.cleanBoilerplate',
  );
}
