// Mocks generated by Mockito 5.4.6 from annotations
// in clean_boilerplate/test/features/auth/domain/usecases/logout_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:clean_boilerplate/config/util/result.dart' as _i4;
import 'package:clean_boilerplate/features/auth/domain/entities/user_entity.dart'
    as _i5;
import 'package:clean_boilerplate/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserEntity>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.Result<_i5.UserEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserEntity>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.UserEntity>> register({
    required String? fullName,
    required String? email,
    required String? password,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #fullName: fullName,
              #email: email,
              #password: password,
              #phone: phone,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.UserEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserEntity>>(
                this,
                Invocation.method(#register, [], {
                  #fullName: fullName,
                  #email: email,
                  #password: password,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserEntity>>);

  @override
  _i3.Future<_i4.Result<void>> forgotPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {#email: email}),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#forgotPassword, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> resetPassword({
    required String? email,
    required String? otp,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #otp: otp,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#resetPassword, [], {
                  #email: email,
                  #otp: otp,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i4.Result<_i5.UserEntity?>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserEntity?>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserEntity?>>);
}
